// Generate the always-loaded four-pillar policy INDEX (a table of contents, not
// policy bodies) from the four pillar SKILL.md `## Policies` sections.
//
// The four `plugins/workaholic/skills/{planning,design,implementation,operation}/SKILL.md`
// files each carry a `## Policies` section: one bullet per policy, `**[Heading](policies/<slug>.md)**
// (日本語) — one-line summary`. Those sections are the single source of the heading
// list (kept in lockstep with qmu.co.jp by the workaholic-standards-sync controller).
// This module concatenates them into one compact digest that `hooks/policy-lens.sh`
// injects so the index is in context on every workflow turn — while the full
// Goal/Responsibility/Practices bodies in `policies/<slug>.md` stay on-demand.
//
// Both build.mjs (writes the committed digest) and verify.mjs (asserts it is fresh)
// import from here so there is exactly one generator.

import { readFileSync } from "node:fs";
import { join } from "node:path";

// Committed, generated; read at runtime by hooks/policy-lens.sh (co-located).
export const POLICY_INDEX_REL = "plugins/workaholic/hooks/policy-index.md";

const PILLARS = [
  ["planning", "Planning (企画)"],
  ["design", "Design (設計)"],
  ["implementation", "Implementation (実装)"],
  ["operation", "Operation (運用)"],
];

// Pull the bullet list under `## Policies` (up to the next `## ` heading) and
// rewrite each relative `policies/<slug>.md` link to a repo-root-navigable path
// so the agent can open a policy body directly from the injected index.
function extractPolicies(repoRoot, pillar) {
  const md = readFileSync(join(repoRoot, "plugins/workaholic/skills", pillar, "SKILL.md"), "utf8");
  const heading = md.indexOf("\n## Policies");
  if (heading === -1) throw new Error(`No '## Policies' section in ${pillar}/SKILL.md`);
  const bodyStart = md.indexOf("\n", heading + 1) + 1;
  const rest = md.slice(bodyStart);
  const nextHeading = rest.indexOf("\n## ");
  const body = (nextHeading === -1 ? rest : rest.slice(0, nextHeading)).trim();
  return body.replace(/\]\(policies\//g, `](plugins/workaholic/skills/${pillar}/policies/`);
}

export function generatePolicyIndex(repoRoot) {
  const sections = PILLARS.map(
    ([slug, title]) => `## ${title}\n\n${extractPolicies(repoRoot, slug)}`
  );
  return `<!-- GENERATED by scripts/build-plugins/policy-index.mjs from the four pillar SKILL.md '## Policies' sections. DO NOT EDIT — regenerate with: node scripts/build-plugins/build.mjs -->

# Workaholic Engineering Policy Index

Always-loaded table of contents for the project's four-pillar engineering policies
(planning 企画 / design 設計 / implementation 実装 / operation 運用). This is the
INDEX only. Open a policy's linked \`policies/<slug>.md\` for its full Goal (目標),
Responsibility (責務), and Practices (実践) when — and only when — your change touches
that policy.

${sections.join("\n\n")}
`;
}
