#!/bin/sh -eu
# CLASSIFY EVERY DIRTY PATH IN THIS CHECKOUT BY PROOF (2026-09-08, mission
# `clear-the-residue-the-base-already-holds-and-never-stop-silently`).
#
#   classify-residue.sh [base-branch]      # base defaults to the branch check.sh calls main
#
# WHY IT EXISTS. `sync-main.sh` §2 refuses `dirty_workspace` on ANY unclean tree, which is
# correct by its own stated rationale — *a reset would discard a developer's local commits* —
# and nothing above it could tell residue that provably discards nothing from residue that
# does. So an unattended tick stalled forever on the first: measured 2026-09-08, 21 ticks over
# ~100 minutes, `sync-main.sh` answering `dirty_workspace` -> `plan-units.sh` answering
# `current: false` -> `claimable-units.sh` answering `readable: false, reason: not_current`,
# with `/implement` never reaching its survey. Six staged paths, four of them blob-identical to
# `origin/main` and two regenerable indexes.
#
# THIS SCRIPT IS THE READING AND NOTHING ELSE. The act that uses it is
# `clear-proved-residue.sh`, deliberately separate: a reader that also writes is a reader
# nobody can run just to look. PURE READ — no commit, no index write, no ref, no fetch, no
# post. It does not fetch precisely because a fetch writes remote-tracking refs, and the
# contract this script keeps is that the index, the worktree and every ref are byte-identical
# across a call. A caller that needs fresher refs fetches first.
#
# THE PROOF FORM IS `superseded`'s, CITED RATHER THAN RE-INVENTED (`drive/reference/claims.md`,
# *Proofs and judgements*): a reading the tree established, which cannot become false when
# re-derived. `on_base` is content equality against the base's own blob; nothing about a
# filename, a directory or a timestamp enters it.
#
# THE FIVE CLASSES, and no class reachable by inference:
#
#   on_base       Both the index entry AND the working-tree file exist and are byte-identical
#                 to `<base>:<path>`. Discarding them loses nothing, because the freshen that
#                 follows fast-forwards the very content back. The test is deliberately
#                 stricter than "the working-tree OR staged blob matches": a path whose two
#                 representations DISAGREE has one side that is not on the base, and that side
#                 is somebody's work.
#   regenerable   The repository's own generator rewrites this path, and the base holds a
#                 version of it. Content is deliberately NOT compared: what this class asserts
#                 is that the file is restorable by running a command, which is a different
#                 (and weaker) proof than content equality — hence its own class rather than a
#                 widening of `on_base`. One class holding both would let a generated file
#                 whose generator is broken read as proved.
#   untracked     Its own class, always. `??` is never anything else.
#   divergent     Tracked, changed, and not equal to the base's blob. A developer's work.
#   unanswerable  The comparison could not be made — no base blob, an unreadable object, a
#                 submodule, a symlink, a rename. AN ABSENCE OF A READING IS NEVER A PROOF, so
#                 this class exists rather than collapsing into `on_base`.
#
# WHICH PATHS ARE GENERATED IS NOT LISTED HERE. Two derivations, both already owned elsewhere:
#   1. `ship/scripts/lib/conflict-class.sh`'s `conflict_class_generated_path` — the repository's
#      ONE home for *this path is generated output*, already coupled by its own header to
#      `refresh-index.sh`'s unconditional `write_index` calls, and already sourced by
#      `drive/scripts/claim-mergeability.sh`. Sourced, never copied: a second list is how two
#      answers to one question drift.
#   2. The marker the generators write into their own output — `<!-- okf:generated:begin -->`
#      (`okf/scripts/refresh-index.sh`) and `<!-- GENERATED by ` (`build-plugins/build.mjs`,
#      which writes `hooks/policy-index.md` this way). Read off the BASE's blob, never the
#      working copy, so residue cannot declare itself regenerable. Self-verifying in the shape
#      `conflict_class_append_only` uses: it covers a file added to the tree tomorrow and can
#      never be wrong about a file it accepts.
#
# THE READER IS BLIND TO *WHY* THE RESIDUE EXISTS. The measured case came from a hand-run
# `git reset`, but reading the reflog for provenance would be reading for a judgement, and none
# of these proofs needs one.
#
# Output (stdout, exit 0):
#   {"ok": true, "base": "origin/<base>",
#    "paths": [{"path": "...", "class": "...", "reason": "..."}],
#    "counts": {"on_base": n, "regenerable": n, "untracked": n, "divergent": n,
#               "unanswerable": n, "total": n}}
#   {"ok": false, "readable": false, "reason": "not_a_repository"|"not_on_main"|"no_origin"
#                                             |"no_base_ref"|"status_unreadable",
#    "base": "...", "paths": null, "counts": null}
#
# `readable` IS ABSENT ON A COMPLETED WALK — the `merge_policy` / `status:` convention this
# repository already holds: absent means it completed, so a consumer tests `readable == false`
# and never `readable // true`. A walk that could not complete answers NULL counts and a NULL
# `paths`, never an empty array, which reads as a clean tree.
#
# Cost: one `git hash-object` per dirty tracked path, plus at most one blob read for a path
# that failed the `on_base` test. The measured tree had six paths.

set -eu

SCRIPT_DIR=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
. "${SCRIPT_DIR}/../../ship/scripts/lib/conflict-class.sh"

requested_base="${1:-}"

emit_unreadable() {
    printf '{"ok": false, "readable": false, "reason": "%s", "base": "%s", "paths": null, "counts": null}\n' \
        "$1" "${2:-}"
    exit 0
}

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    echo '{"error": "not inside a git repository"}' >&2
    exit 1
fi

# --- The base branch ---------------------------------------------------------------------
# Resolved the way `sync-main.sh` resolves it, through the same reader, so the two can never
# disagree about which branch is the base.
if [ -n "$requested_base" ]; then
    base="$requested_base"
else
    check_out=$(sh "${SCRIPT_DIR}/check.sh")
    branch=$(printf '%s\n' "$check_out" | sed -n 's/.*"branch":[ ]*"\([^"]*\)".*/\1/p')
    on_main=$(printf '%s\n' "$check_out" | sed -n 's/.*"on_main":[ ]*\([a-z]*\).*/\1/p')
    if [ "$on_main" = "true" ]; then
        base="$branch"
    else
        base=""
        for candidate in main master; do
            if git rev-parse --verify --quiet "refs/remotes/origin/${candidate}" >/dev/null 2>&1; then
                base="$candidate"
                break
            fi
        done
        [ -n "$base" ] || emit_unreadable not_on_main ""
    fi
fi

git config --get remote.origin.url >/dev/null 2>&1 || emit_unreadable no_origin "origin/${base}"
base_ref="refs/remotes/origin/${base}"
git rev-parse --verify --quiet "${base_ref}^{commit}" >/dev/null 2>&1 \
    || emit_unreadable no_base_ref "origin/${base}"

# The NUL separators are turned into newlines INSIDE the substitution, because command
# substitution drops NUL bytes outright — capturing the raw `-z` stream into a variable and
# translating afterwards silently concatenates every record into one.
status=$(git status --porcelain -z 2>/dev/null | tr '\0' '\n') \
    || emit_unreadable status_unreadable "origin/${base}"

# --- Per-path classification ---------------------------------------------------------------

json_escape() {
    printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/\t/\\t/g'
}

# Does the base's own copy of this path carry a generator's marker? Read from the blob, capped
# to the head of the file: every generator this repository has writes its marker on line 1.
base_blob_is_marked() {
    _cbm=$(git cat-file blob "$1" 2>/dev/null | head -c 4096 || true)
    case "$_cbm" in
        *'<!-- okf:generated:begin -->'*) return 0 ;;
        *'<!-- GENERATED by '*) return 0 ;;
        *) return 1 ;;
    esac
}

n_on_base=0
n_regenerable=0
n_untracked=0
n_divergent=0
n_unanswerable=0
entries=""

add_entry() {
    _ae_path=$(json_escape "$1")
    if [ -n "$entries" ]; then
        entries="${entries},"
    fi
    entries="${entries}{\"path\": \"${_ae_path}\", \"class\": \"$2\", \"reason\": \"$3\"}"
}

classify_one() {
    _co_xy="$1"
    _co_path="$2"

    case "$_co_xy" in
        '??')
            n_untracked=$((n_untracked + 1))
            add_entry "$_co_path" untracked untracked
            return 0
            ;;
    esac

    if [ -L "$_co_path" ]; then
        n_unanswerable=$((n_unanswerable + 1))
        add_entry "$_co_path" unanswerable symlink
        return 0
    fi

    _co_base_entry=$(git ls-tree "$base_ref" -- "$_co_path" 2>/dev/null || true)
    if [ -z "$_co_base_entry" ]; then
        n_unanswerable=$((n_unanswerable + 1))
        add_entry "$_co_path" unanswerable no_base_blob
        return 0
    fi

    _co_base_mode=$(printf '%s' "$_co_base_entry" | awk '{print $1}')
    case "$_co_base_mode" in
        160000|120000)
            n_unanswerable=$((n_unanswerable + 1))
            add_entry "$_co_path" unanswerable non_regular_base_entry
            return 0
            ;;
    esac
    _co_base_blob=$(printf '%s' "$_co_base_entry" | awk '{print $3}')
    if [ -z "$_co_base_blob" ]; then
        n_unanswerable=$((n_unanswerable + 1))
        add_entry "$_co_path" unanswerable no_base_blob
        return 0
    fi

    # `on_base` is the stronger proof and is tested first, so a path that is both proved and
    # generated takes the stronger class. The outcome is identical either way.
    _co_index_blob=$(git rev-parse --verify --quiet ":${_co_path}" 2>/dev/null || true)
    _co_wt_blob=""
    if [ -f "$_co_path" ]; then
        _co_wt_blob=$(git hash-object -- "$_co_path" 2>/dev/null || true)
    fi

    if [ -n "$_co_index_blob" ] && [ -n "$_co_wt_blob" ] \
        && [ "$_co_index_blob" = "$_co_base_blob" ] && [ "$_co_wt_blob" = "$_co_base_blob" ]; then
        n_on_base=$((n_on_base + 1))
        add_entry "$_co_path" on_base blob_equals_base
        return 0
    fi

    if conflict_class_generated_path "$_co_path"; then
        n_regenerable=$((n_regenerable + 1))
        add_entry "$_co_path" regenerable generated_path
        return 0
    fi
    if base_blob_is_marked "$_co_base_blob"; then
        n_regenerable=$((n_regenerable + 1))
        add_entry "$_co_path" regenerable generated_marker
        return 0
    fi

    n_divergent=$((n_divergent + 1))
    if [ -z "$_co_wt_blob" ]; then
        add_entry "$_co_path" divergent absent_from_worktree
    elif [ -z "$_co_index_blob" ]; then
        add_entry "$_co_path" divergent absent_from_index
    else
        add_entry "$_co_path" divergent blob_differs_from_base
    fi
}

# `git status --porcelain -z` emits NUL-separated records of the form "XY path", with paths
# UNQUOTED — which is why `-z` is used rather than the quoting form, whose escapes would have to
# be un-escaped here. A rename or copy emits a SECOND record holding the original path alone;
# it carries no XY prefix, so it is skipped by the flag below rather than parsed as a path of
# its own. The rename itself is `unanswerable`: it is a developer's move and no blob comparison
# answers it.
#
# STATED RESIDUE: converting NUL to newline to iterate misparses a path containing a literal
# newline. Such a path is not silently mis-classified into a clearable class — the arms above
# are keyed on a base blob that will not resolve for the mangled name, so it lands in
# `unanswerable`, which is the safe direction.
if [ -n "$status" ]; then
    skip_next=false
    old_ifs=$IFS
    IFS='
'
    for record in $status; do
        if [ "$skip_next" = true ]; then
            skip_next=false
            continue
        fi
        [ -n "$record" ] || continue
        xy=$(printf '%s' "$record" | cut -c1-2)
        path=$(printf '%s' "$record" | cut -c4-)
        [ -n "$path" ] || continue
        case "$xy" in
            R*|*R|C*|*C)
                skip_next=true
                n_unanswerable=$((n_unanswerable + 1))
                add_entry "$path" unanswerable rename_or_copy
                continue
                ;;
        esac
        classify_one "$xy" "$path"
    done
    IFS=$old_ifs
fi

total=$((n_on_base + n_regenerable + n_untracked + n_divergent + n_unanswerable))

printf '{"ok": true, "base": "origin/%s", "paths": [%s], "counts": {"on_base": %d, "regenerable": %d, "untracked": %d, "divergent": %d, "unanswerable": %d, "total": %d}}\n' \
    "$base" "$entries" "$n_on_base" "$n_regenerable" "$n_untracked" "$n_divergent" "$n_unanswerable" "$total"
